package vision

import (
	"fmt"
	"math"
	"os"
	"testing"

	"github.com/jxsl13/goai/backend"
	"github.com/jxsl13/goai/format/safetensors"
	"github.com/jxsl13/goai/tensor"
)

// vitParityModel builds the fixed tiny ViT (seed 7, F64) and its fixed input —
// the configuration the torch golden below was generated from.
func vitParityModel(t *testing.T) (*ViT, *tensor.Tensor) {
	t.Helper()
	m, err := NewViT(1, 8, 3, 7, WithViTDtype(tensor.F64))
	if err != nil {
		t.Fatal(err)
	}
	img := tensor.New(tensor.F64, tensor.Shape{1, 8, 8})
	s := img.Storage().F64()
	for i := range s {
		s[i] = math.Sin(float64(3*(i/8)+i%8)) / 2
	}
	return m, img
}

// TestViTTorchParity (§V16 tier-1, §T590): the Go forward pass reproduces the
// torch reference implementation of the same architecture on identical weights.
// Golden generated by exporting the seed-7 weights via VIT_PARITY_DUMP and
// rebuilding the model in torch 2.x at f64 (see testdata/gen.py provenance
// note); tolerance is relative 1e-9 (§B-class libm last-digit differences).
func TestViTTorchParity(t *testing.T) {
	m, img := vitParityModel(t)
	if dump := os.Getenv("VIT_PARITY_DUMP"); dump != "" {
		out := map[string]*tensor.Tensor{
			"img": img, "class": m.Class, "pos": m.Pos,
			"embed.w": m.Embed.W, "embed.b": m.Embed.B,
			"norm.g": m.Norm.Gamma, "norm.b": m.Norm.Beta,
			"head.w": m.Head.W, "head.b": m.Head.B,
		}
		for i, b := range m.Blocks {
			p := fmt.Sprintf("blk%d.", i)
			out[p+"wq"], out[p+"wk"], out[p+"wv"], out[p+"wo"] = b.attn.Wq, b.attn.Wk, b.attn.Wv, b.attn.Wo
			out[p+"ln1.g"], out[p+"ln1.b"] = b.ln1.Gamma, b.ln1.Beta
			out[p+"ln2.g"], out[p+"ln2.b"] = b.ln2.Gamma, b.ln2.Beta
			out[p+"fc1.w"], out[p+"fc1.b"] = b.fc1.W, b.fc1.B
			out[p+"fc2.w"], out[p+"fc2.b"] = b.fc2.W, b.fc2.B
		}
		if err := safetensors.SaveFile(dump, out, nil); err != nil {
			t.Fatal(err)
		}
	}
	logits, err := m.Forward(backend.NewContext(), img)
	if err != nil {
		t.Fatal(err)
	}
	got := logits.Storage().F64()
	// torch 2.x f64 golden for the seed-7 model on the fixed sine image
	// (manual torch reference: patch-embed → class+pos → 2 pre-LN blocks with
	// 4-head SDPA and exact-erf GELU MLP → LN → head; agreed to 15 digits).
	want := []float64{2.04940375622606, -2.40905239477869, 0.818562684403547}
	for i := range want {
		tol := 1e-9 * math.Max(1, math.Abs(want[i]))
		if math.Abs(got[i]-want[i]) > tol {
			t.Errorf("logit %d: got %.15g, want %.15g", i, got[i], want[i])
		}
	}
}
