package gguf

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/jxsl13/goai/tensor"
)

// §T554 §V16 tier-1: the Go IQ2_XXS dequant must match gguf-py (the llama.cpp
// project's own reference library) EXACTLY on random blocks — golden vectors
// generated by testdata/iq2xxs_golden.json's committed gguf-py run (seed 42,
// 4 blocks). f32-exact: both implementations compute d·(0.5+s)·0.25·grid·sign
// in float32.
func TestIQ2XXSDequantMatchesGGUFPy(t *testing.T) {
	raw, err := os.ReadFile("testdata/iq2xxs_golden.json")
	if err != nil {
		t.Skip("golden missing (generate via gguf-py):", err)
	}
	var golden struct {
		Data []byte    `json:"data"`
		Want []float32 `json:"want"`
	}
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatal(err)
	}
	n := len(golden.Want)
	got, err := Dequantize(golden.Data, IQ2_XXS, n)
	if err != nil {
		t.Fatal(err)
	}
	g := got.Storage().F32()
	for i := range n {
		if g[i] != golden.Want[i] {
			t.Fatalf("[%d]: go %g vs gguf-py %g", i, g[i], golden.Want[i])
		}
	}
}

// Hostile-input contract (§B47 discipline): arbitrary bytes must dequantize or
// error, never panic; wrong sizes must error.
func TestIQ2XXSHostile(t *testing.T) {
	if _, err := Dequantize(make([]byte, 65), IQ2_XXS, 256); err == nil {
		t.Fatal("short data must error")
	}
	if _, err := Dequantize(make([]byte, 66), IQ2_XXS, 100); err == nil {
		t.Fatal("non-multiple numel must error")
	}
	junk := make([]byte, 66)
	for i := range junk {
		junk[i] = byte(i*37 + 251)
	}
	out, err := Dequantize(junk, IQ2_XXS, 256)
	if err != nil {
		t.Fatal(err)
	}
	if !out.Shape().Equal(tensor.Shape{256}) {
		t.Fatalf("shape %v", out.Shape())
	}
}

// FuzzDequantIQ2XXS: any byte soup of block size must decode without panicking
// (every qs0 byte indexes the full 256-entry grid, every 7-bit field the full
// ksigns table — total functions by construction; the fuzzer guards regressions).
func FuzzDequantIQ2XXS(f *testing.F) {
	f.Add(make([]byte, 66))
	f.Fuzz(func(t *testing.T, data []byte) {
		if len(data) < 66 {
			return
		}
		data = data[:66]
		defer func() {
			if r := recover(); r != nil {
				t.Fatalf("panicked: %v", r)
			}
		}()
		_, _ = Dequantize(data, IQ2_XXS, 256)
	})
}
