package gguf

import (
	"bytes"
	"encoding/binary"
	"math"
	"testing"

	"github.com/jxsl13/goai/tensor"
)

func TestQ41WireGolden(t *testing.T) {
	values := make([]float32, blockElems)
	for i := range values {
		values[i] = float32(i % 16)
	}
	got, err := Quantize(tensor.FromFloat32(tensor.Shape{blockElems}, values), Q4_1)
	if err != nil {
		t.Fatal(err)
	}
	want := []byte{
		0x00, 0x3c, // d = 1
		0x00, 0x00, // m = 0
		0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
		0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("Q4_1 wire bytes = % x, want % x", got, want)
	}
	decoded, err := Dequantize(got, Q4_1, blockElems)
	if err != nil {
		t.Fatal(err)
	}
	for i, want := range values {
		if got := decoded.Storage().F32()[i]; got != want {
			t.Fatalf("decoded[%d] = %v, want %v", i, got, want)
		}
	}
}

func TestQ41PinnedLlamaFixture(t *testing.T) {
	// Generated by quantize_row_q4_1 from pinned llama.cpp commit
	// 3af988fabcf79fd81f8720505e684d2aa5bfc786. This non-grid block catches
	// extrema selection, rounding, f16 headers, and split-half nibble packing.
	values := []float32{
		-3.25, 5.5, -2.875, 4.75, -1.5, 3.125, -0.25, 2,
		0.125, 1.375, -2, 4, -0.875, 2.75, 0.75, 5,
		-3, 5.25, -2.5, 4.5, -1.25, 3.5, -0.5, 2.25,
		0.375, 1.625, -1.75, 3.75, -0.625, 2.5, 1, 4.25,
	}
	want := []byte{
		0xab, 0x38, 0x80, 0xc2,
		0x00, 0xff, 0x11, 0xde, 0x33, 0xcb, 0x55, 0x99,
		0x66, 0x88, 0x32, 0xcc, 0x54, 0xaa, 0x77, 0xde,
	}
	got, err := Quantize(tensor.FromFloat32(tensor.Shape{blockElems}, values), Q4_1)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("Q4_1 pinned fixture = % x, want % x", got, want)
	}
}

func TestQ41ConstantBlock(t *testing.T) {
	values := make([]float32, blockElems)
	for i := range values {
		values[i] = -2
	}
	raw, err := Quantize(tensor.FromFloat32(tensor.Shape{blockElems}, values), Q4_1)
	if err != nil {
		t.Fatal(err)
	}
	if d := binary.LittleEndian.Uint16(raw[0:2]); d != 0 {
		t.Fatalf("constant block d = %#04x, want zero", d)
	}
	if m := binary.LittleEndian.Uint16(raw[2:4]); m != f32ToF16(-2) {
		t.Fatalf("constant block m = %#04x, want %#04x", m, f32ToF16(-2))
	}
	if !bytes.Equal(raw[4:], make([]byte, blockElems/2)) {
		t.Fatalf("constant block quants = % x, want all zero", raw[4:])
	}
	decoded, err := Dequantize(raw, Q4_1, blockElems)
	if err != nil {
		t.Fatal(err)
	}
	for i, got := range decoded.Storage().F32() {
		if got != -2 {
			t.Fatalf("decoded[%d] = %v, want -2", i, got)
		}
	}
}

func TestQ41ArbitraryRawDecode(t *testing.T) {
	raw := make([]byte, q41BlockSize)
	binary.LittleEndian.PutUint16(raw[0:2], f32ToF16(0.25))
	binary.LittleEndian.PutUint16(raw[2:4], f32ToF16(-1.5))
	for i := range blockElems / 2 {
		raw[4+i] = byte(i) | byte(15-i)<<4
	}
	decoded, err := Dequantize(raw, Q4_1, blockElems)
	if err != nil {
		t.Fatal(err)
	}
	values := decoded.Storage().F32()
	for i := range blockElems / 2 {
		if got, want := values[i], -1.5+0.25*float32(i); got != want {
			t.Fatalf("low[%d] = %v, want %v", i, got, want)
		}
		if got, want := values[i+blockElems/2], -1.5+0.25*float32(15-i); got != want {
			t.Fatalf("high[%d] = %v, want %v", i, got, want)
		}
	}
}

func makeQ41Raw(elements int) []byte {
	values := make([]float32, elements)
	for i := range values {
		values[i] = float32(math.Sin(float64(i)*0.17) * math.Pow(2, float64(i%9-4)))
	}
	raw, err := Quantize(tensor.FromFloat32(tensor.Shape{elements}, values), Q4_1)
	if err != nil {
		panic(err)
	}
	return raw
}

func TestDequantQ41IntoMatchesTensorPathExactly(t *testing.T) {
	const elements = 256
	raw := makeQ41Raw(elements)
	want, err := dequantQ4_1(tensor.Shape{elements}, raw)
	if err != nil {
		t.Fatal(err)
	}
	got := make([]float32, elements)
	dequantQ4_1Into(got, raw)
	for i, value := range got {
		if math.Float32bits(value) != math.Float32bits(want.Storage().F32()[i]) {
			t.Fatalf("[%d]: into %v (%#08x), tensor %v (%#08x)", i, value, math.Float32bits(value), want.Storage().F32()[i], math.Float32bits(want.Storage().F32()[i]))
		}
	}
}

func TestDotQ41RowMatchesMaterializedReferenceExactly(t *testing.T) {
	const k = 4096
	raw := makeQ41Raw(k)
	x := make([]float32, k)
	for i := range x {
		x[i] = float32(math.Cos(float64(i)*0.11) * math.Pow(2, float64(i%7-3)))
	}
	w := make([]float32, k)
	dequantQ4_1Into(w, raw)
	var want float64
	for i, value := range w {
		want += float64(x[i]) * float64(value)
	}
	got := dotQ41Row(x, raw, k)
	if math.Float64bits(got) != math.Float64bits(want) {
		t.Fatalf("fused %v (%#016x), materialized %v (%#016x)", got, math.Float64bits(got), want, math.Float64bits(want))
	}
}

func TestQMatMulQ41MatchesDequantizedReference(t *testing.T) {
	const n, k = 3, 256
	raw := makeQ41Raw(n * k)
	weights, err := dequantQ4_1(tensor.Shape{n, k}, raw)
	if err != nil {
		t.Fatal(err)
	}
	wf := weights.Storage().F32()
	for _, tc := range []struct {
		name string
		m    int
		f64  bool
	}{{"F32_M1", 1, false}, {"F32_M3", 3, false}, {"F64_M1", 1, true}, {"F64_M3", 3, true}} {
		t.Run(tc.name, func(t *testing.T) {
			var x *tensor.Tensor
			var x32 []float32
			var x64 []float64
			if tc.f64 {
				x64 = make([]float64, tc.m*k)
				for i := range x64 {
					x64[i] = math.Sin(float64(i)*0.19) * math.Pow(2, float64(i%7-3))
				}
				x = tensor.FromFloat64(tensor.Shape{tc.m, k}, x64)
			} else {
				x32 = make([]float32, tc.m*k)
				for i := range x32 {
					x32[i] = float32(math.Sin(float64(i)*0.19) * math.Pow(2, float64(i%7-3)))
				}
				x = tensor.FromFloat32(tensor.Shape{tc.m, k}, x32)
			}
			got, err := QMatMul(x, raw, Q4_1, n, k)
			if err != nil {
				t.Fatal(err)
			}
			for mi := range tc.m {
				for ni := range n {
					var want float64
					for ki := range k {
						activation := x.AtF64(mi, ki)
						want += activation * float64(wf[ni*k+ki])
					}
					gotv, wantv := got.Storage().F32()[mi*n+ni], float32(want)
					delta := math.Abs(float64(gotv - wantv))
					if delta > 2e-5+2e-5*math.Abs(float64(wantv)) {
						t.Fatalf("m=%d n=%d: got=%v want=%v delta=%g", mi, ni, gotv, wantv, delta)
					}
				}
			}
		})
	}
}

var q41QMatMulSink *tensor.Tensor

func TestQMatMulQ41ScratchAllocationsDoNotScaleWithOutputRows(t *testing.T) {
	const m, k = 2, blockElems
	x := tensor.New(tensor.F32, tensor.Shape{m, k})
	allocs := func(n int) float64 {
		raw := makeQ41Raw(n * k)
		return testing.AllocsPerRun(100, func() {
			var err error
			q41QMatMulSink, err = QMatMul(x, raw, Q4_1, n, k)
			if err != nil {
				panic(err)
			}
		})
	}
	one, many := allocs(1), allocs(31)
	if many != one {
		t.Fatalf("QMatMul allocations scale with output rows: N1=%g N31=%g", one, many)
	}
}

func TestQMatMulQ41SelectorScope(t *testing.T) {
	const n, k = 3, blockElems
	raw := makeQ41Raw(n * k)
	old := dotQ41RowFn
	defer func() { dotQ41RowFn = old }()
	calls := 0
	dotQ41RowFn = func(row []float32, weight []byte, width int) float64 {
		calls++
		return dotQ41Row(row, weight, width)
	}
	if _, err := QMatMul(tensor.New(tensor.F32, tensor.Shape{1, k}), raw, Q4_1, n, k); err != nil {
		t.Fatal(err)
	}
	if calls != n {
		t.Fatalf("contiguous F32 M1 selector calls = %d, want %d", calls, n)
	}
	calls = 0
	if _, err := QMatMul(tensor.New(tensor.F32, tensor.Shape{2, k}), raw, Q4_1, n, k); err != nil {
		t.Fatal(err)
	}
	if calls != 0 {
		t.Fatalf("F32 M2 dispatched M1 row leaf %d times", calls)
	}
	if _, err := QMatMul(tensor.New(tensor.F64, tensor.Shape{1, k}), raw, Q4_1, n, k); err != nil {
		t.Fatal(err)
	}
	if calls != 0 {
		t.Fatalf("F64 M1 dispatched F32 row leaf %d times", calls)
	}
}

func TestQ41RoundTripBound(t *testing.T) {
	const n = 96
	x := tensor.FromFloat64(tensor.Shape{n}, randF32Block(n, 41))
	raw, err := Quantize(x, Q4_1)
	if err != nil {
		t.Fatal(err)
	}
	decoded, err := Dequantize(raw, Q4_1, n)
	if err != nil {
		t.Fatal(err)
	}
	for b := range n / blockElems {
		minv, maxv := math.Inf(1), math.Inf(-1)
		for i := range blockElems {
			v := x.AtF64(b*blockElems + i)
			if v < minv {
				minv = v
			}
			if v > maxv {
				maxv = v
			}
		}
		bound := (maxv-minv)/30 + max(math.Abs(minv), math.Abs(maxv))*0.002
		for i := range blockElems {
			at := b*blockElems + i
			if delta := math.Abs(float64(decoded.Storage().F32()[at]) - x.AtF64(at)); delta > bound {
				t.Fatalf("block=%d value=%d error=%g, bound=%g", b, i, delta, bound)
			}
		}
	}
}

func TestQ41ReadWriteRawFlow(t *testing.T) {
	w := tensor.FromFloat64(tensor.Shape{2, blockElems}, randF32Block(2*blockElems, 42))
	f := &File{
		Version:  3,
		Metadata: map[string]any{"general.architecture": "q41-test"},
		Tensors:  map[string]*tensor.Tensor{"w": w},
	}
	var encoded bytes.Buffer
	if err := WriteQuantized(&encoded, f, map[string]QuantType{"w": Q4_1}); err != nil {
		t.Fatal(err)
	}
	eager, err := Read(bytes.NewReader(encoded.Bytes()))
	if err != nil {
		t.Fatal(err)
	}
	rawFile, err := ReadRaw(bytes.NewReader(encoded.Bytes()))
	if err != nil {
		t.Fatal(err)
	}
	qt := rawFile.Tensors["w"]
	if qt.GGType != uint32(Q4_1) {
		t.Fatalf("wire type = %d, want Q4_1 type 3", qt.GGType)
	}
	if len(qt.Data) != 2*q41BlockSize {
		t.Fatalf("raw length = %d, want %d", len(qt.Data), 2*q41BlockSize)
	}
	wantRaw, err := Quantize(w, Q4_1)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(qt.Data, wantRaw) {
		t.Fatal("WriteQuantized Q4_1 payload differs from Quantize")
	}
	fromRaw, err := qt.Dequantize()
	if err != nil {
		t.Fatal(err)
	}
	for i := range w.Numel() {
		idx := tensor.Unravel(i, w.Shape())
		if got, want := fromRaw.AtF64(idx...), eager.Tensors["w"].AtF64(idx...); got != want {
			t.Fatalf("value %d: raw=%v eager=%v", i, got, want)
		}
	}
}

func TestQ41RejectsMisalignedData(t *testing.T) {
	if got, err := byteSize(3, 64); err != nil || got != 2*q41BlockSize {
		t.Fatalf("byteSize(type=3,n=64) = %d, %v", got, err)
	}
	if _, err := byteSize(3, 33); err == nil {
		t.Fatal("byteSize accepted a non-block-aligned Q4_1 dimension")
	}
	if _, err := Quantize(tensor.New(tensor.F32, tensor.Shape{33}), Q4_1); err == nil {
		t.Fatal("Quantize accepted a non-block-aligned Q4_1 tensor")
	}
	if _, err := Dequantize(make([]byte, q41BlockSize-1), Q4_1, blockElems); err == nil {
		t.Fatal("Dequantize accepted a short Q4_1 block")
	}
	x := tensor.New(tensor.F32, tensor.Shape{1, blockElems})
	if _, err := QMatMul(x, make([]byte, q41BlockSize-1), Q4_1, 1, blockElems); err == nil {
		t.Fatal("QMatMul accepted a short Q4_1 row")
	}
}
