package gguf

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"math"
	"slices"
	"testing"

	"github.com/jxsl13/goai/tensor"
)

func makeTQ2Raw(n int) []byte {
	x := make([]float32, n)
	for i := range x {
		x[i] = float32((i*19+i/11)%3 - 1)
	}
	return quantizeTQ2_0(x)
}

func TestTQ2LayoutAndKnownCodes(t *testing.T) {
	if TQ2_0 != 35 || tq2BlockElems != 256 || tq2BlockSize != 66 {
		t.Fatalf("TQ2_0 layout = type %d, elems %d, bytes %d", TQ2_0, tq2BlockElems, tq2BlockSize)
	}
	for _, tc := range []struct {
		name   string
		packed byte
		want   float32
	}{{"negative", 0x00, -0.5}, {"zero", 0x55, 0}, {"positive", 0xaa, 0.5}, {"raw_code_3", 0xff, 1}} {
		t.Run(tc.name, func(t *testing.T) {
			raw := make([]byte, tq2BlockSize)
			for i := 0; i < tq2PackedBytes; i++ {
				raw[i] = tc.packed
			}
			binary.LittleEndian.PutUint16(raw[tq2PackedBytes:], f32ToF16(0.5))
			got, err := Dequantize(raw, TQ2_0, tq2BlockElems)
			if err != nil {
				t.Fatal(err)
			}
			for i, v := range got.Storage().F32() {
				if v != tc.want {
					t.Fatalf("value[%d] = %v, want %v", i, v, tc.want)
				}
			}
		})
	}
}

func TestTQ2DecodeEntryPointsAgree(t *testing.T) {
	raw := makeTQ2Raw(2 * tq2BlockElems)
	shape := tensor.Shape{2, tq2BlockElems}
	public, err := Dequantize(raw, TQ2_0, shape.Numel())
	if err != nil {
		t.Fatal(err)
	}
	rawTensor, err := (QuantTensor{Data: raw, GGType: tTQ2_0, Shape: shape}).Dequantize()
	if err != nil {
		t.Fatal(err)
	}
	eager, err := decodeTensor(tensorInfo{name: "tq2", shape: shape, ggType: tTQ2_0}, raw)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(public.Storage().F32(), rawTensor.Storage().F32()) ||
		!slices.Equal(public.Storage().F32(), eager.Storage().F32()) {
		t.Fatal("TQ2_0 eager, raw, and public decoders disagree")
	}
}

func TestQuantizeTQ2MatchesPinnedReferenceBytes(t *testing.T) {
	x := make([]float32, tq2BlockElems)
	for i := range x {
		x[i] = float32((i*19+i/11)%3 - 1)
	}
	before := slices.Clone(x)
	got, err := Quantize(tensor.FromFloat32(tensor.Shape{len(x)}, x), TQ2_0)
	if err != nil {
		t.Fatal(err)
	}
	// Generated by quantize_row_tq2_0_ref at pinned llama.cpp commit
	// 3af988fabcf79fd81f8720505e684d2aa5bfc786.
	want, err := hex.DecodeString("84114618618618618618618411461861861861861861841146186186186186186186186184114618618618618618618411461861861861861861841146186186003c")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("TQ2_0 bytes = %x, want pinned llama.cpp bytes %x", got, want)
	}
	if !slices.Equal(x, before) {
		t.Fatal("Quantize modified its input")
	}
}

func TestDotTQ2RowMatchesMaterializedDecodeExactly(t *testing.T) {
	for _, k := range []int{tq2BlockElems, 4 * tq2BlockElems, 16 * tq2BlockElems} {
		raw := makeTQ2Raw(k)
		weights := make([]float32, k)
		dequantTQ2_0Into(weights, raw)
		row := make([]float32, k)
		for i := range row {
			row[i] = float32(math.Cos(float64(i)*0.071) * 3)
		}
		var want float64
		for i, w := range weights {
			want += float64(row[i]) * float64(w)
		}
		if got := dotTQ2Row(row, raw, k); got != want {
			t.Fatalf("K=%d fused dot = %.17g, materialized = %.17g", k, got, want)
		}
	}
}

func TestTQ2RejectsInvalidInputs(t *testing.T) {
	if _, err := Dequantize(make([]byte, tq2BlockSize), TQ2_0, tq2BlockElems-1); err == nil {
		t.Fatal("Dequantize accepted non-block-aligned TQ2_0 values")
	}
	if _, err := Dequantize(make([]byte, tq2BlockSize-1), TQ2_0, tq2BlockElems); err == nil {
		t.Fatal("Dequantize accepted truncated TQ2_0 data")
	}
	if _, err := Quantize(tensor.New(tensor.F32, tensor.Shape{tq2BlockElems - 1}), TQ2_0); err == nil {
		t.Fatal("Quantize accepted a non-block-aligned tensor")
	}
}
