package classic

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"testing"
)

// --- golden loader (mirrors loadClassic; separate file classic/testdata/gbm.json
// generated by classic/testdata/gen_gbm.py against real sklearn, §V1) ---

type gbmGoldenReg struct {
	NTrain       int       `json:"n_train"`
	NTest        int       `json:"n_test"`
	D            int       `json:"d"`
	NEstimators  int       `json:"n_estimators"`
	LearningRate float64   `json:"learning_rate"`
	MaxDepth     int       `json:"max_depth"`
	XTrain       []float64 `json:"X_train"`
	YTrain       []float64 `json:"y_train"`
	XTest        []float64 `json:"X_test"`
	YTest        []float64 `json:"y_test"`
	Init         float64   `json:"init"`
	PredTest     []float64 `json:"pred_test"`
	R2Test       float64   `json:"r2_test"`
}

type gbmGoldenClf struct {
	NTrain       int       `json:"n_train"`
	NTest        int       `json:"n_test"`
	D            int       `json:"d"`
	NEstimators  int       `json:"n_estimators"`
	LearningRate float64   `json:"learning_rate"`
	MaxDepth     int       `json:"max_depth"`
	XTrain       []float64 `json:"X_train"`
	YTrain       []int     `json:"y_train"`
	XTest        []float64 `json:"X_test"`
	YTest        []int     `json:"y_test"`
	BaseRate     float64   `json:"base_rate"`
	InitLogodds  float64   `json:"init_logodds"`
	ProbTest     []float64 `json:"prob_test"`
	PredTest     []int     `json:"pred_test"`
	AccuracyTest float64   `json:"accuracy_test"`
}

type gbmGolden struct {
	Regressor  gbmGoldenReg `json:"regressor"`
	Classifier gbmGoldenClf `json:"classifier"`
	Sklearn    string       `json:"sklearn"`
}

func gbmLoadGolden(t *testing.T) gbmGolden {
	t.Helper()
	raw, err := os.ReadFile("testdata/gbm.json")
	if err != nil {
		t.Fatalf("read gbm golden (run `.venv/bin/python classic/testdata/gen_gbm.py`): %v", err)
	}
	var g gbmGolden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

func gbmRows(flat []float64, n, d int) [][]float64 {
	out := make([][]float64, n)
	for i := range n {
		out[i] = flat[i*d : (i+1)*d]
	}
	return out
}

func gbmR2(y, pred []float64) float64 {
	var mean float64
	for _, v := range y {
		mean += v
	}
	mean /= float64(len(y))
	var ssRes, ssTot float64
	for i := range y {
		ssRes += (y[i] - pred[i]) * (y[i] - pred[i])
		ssTot += (y[i] - mean) * (y[i] - mean)
	}
	return 1 - ssRes/ssTot
}

// §V16-EQUIV ANCHOR 1 (SKLEARN GOLDEN PARITY, regressor). Match sklearn's
// GradientBoostingRegressor on a Friedman #1 dataset with identical
// hyper-parameters. Exact per-prediction bit-match against sklearn's Cython
// friedman_mse trees is unrealistic: tiny differences in float summation order
// and split tie-breaking at any node change which threshold wins by a hair, and
// that choice cascades through 100 stagewise trees. We therefore assert the
// robust, order-insensitive anchors: (a) test-set R² parity to 1e-2 (both models
// generalise identically, here 0.850 vs 0.851) and (b) the MEAN prediction gap
// stays a tiny fraction of the target spread. These are documented tolerances,
// not bit-equality.
func TestGBMRegressorSklearnParity(t *testing.T) {
	g := gbmLoadGolden(t).Regressor
	xtr := gbmRows(g.XTrain, g.NTrain, g.D)
	xte := gbmRows(g.XTest, g.NTest, g.D)
	m := NewGradientBoostingRegressor(
		WithGBMNEstimators(g.NEstimators), WithGBMLearningRate(g.LearningRate),
		WithGBMMaxDepth(g.MaxDepth))
	if err := m.Fit(xtr, g.YTrain); err != nil {
		t.Fatal(err)
	}
	if math.Abs(m.init-g.Init) > 1e-9*math.Max(1, math.Abs(g.Init)) {
		t.Errorf("init F_0: got %.12g want %.12g", m.init, g.Init)
	}
	pred, err := m.Predict(xte)
	if err != nil {
		t.Fatal(err)
	}
	r2 := gbmR2(g.YTest, pred)
	if math.Abs(r2-g.R2Test) > 1e-2 {
		t.Errorf("test R²: got %.6f want %.6f (Δ=%.2g > 1e-2)", r2, g.R2Test, math.Abs(r2-g.R2Test))
	}
	// per-prediction closeness relative to the target spread: the MEAN gap must
	// be a small fraction of spread (max is logged; a few points differ more due
	// to threshold cascades, which is why the mean — not the max — is asserted).
	var lo, hi = math.Inf(1), math.Inf(-1)
	for _, v := range g.YTest {
		lo, hi = math.Min(lo, v), math.Max(hi, v)
	}
	spread := hi - lo
	var sumAbs, maxAbs float64
	for i := range pred {
		d := math.Abs(pred[i] - g.PredTest[i])
		sumAbs += d
		maxAbs = math.Max(maxAbs, d)
	}
	meanAbs := sumAbs / float64(len(pred))
	if meanAbs > 1e-2*spread {
		t.Errorf("mean |pred−sklearn| = %.4g > 1e-2·spread (%.4g)", meanAbs, 1e-2*spread)
	}
	t.Logf("sklearn %s: R² go=%.5f sklearn=%.5f; mean|Δpred|=%.3g max=%.3g (spread %.3g)",
		gbmLoadGolden(t).Sklearn, r2, g.R2Test, meanAbs, maxAbs, spread)
}

// §V16-EQUIV ANCHOR 1 (SKLEARN GOLDEN PARITY, classifier). Our classifier fits
// regression trees to the log-loss gradient with leaf = mean residual and omits
// sklearn's per-leaf Newton refinement, so exact probability match is not
// expected. We assert ACCURACY parity (the documented tolerance) on a two-moons
// test set plus high label agreement with sklearn.
func TestGBMClassifierSklearnParity(t *testing.T) {
	g := gbmLoadGolden(t).Classifier
	xtr := gbmRows(g.XTrain, g.NTrain, g.D)
	xte := gbmRows(g.XTest, g.NTest, g.D)
	m := NewGradientBoostingClassifier(
		WithGBMNEstimators(g.NEstimators), WithGBMLearningRate(g.LearningRate),
		WithGBMMaxDepth(g.MaxDepth))
	if err := m.Fit(xtr, g.YTrain); err != nil {
		t.Fatal(err)
	}
	if math.Abs(m.init-g.InitLogodds) > 1e-9 {
		t.Errorf("init log-odds: got %.12g want %.12g", m.init, g.InitLogodds)
	}
	pred, err := m.Predict(xte)
	if err != nil {
		t.Fatal(err)
	}
	var correct, agree int
	for i := range pred {
		if pred[i] == g.YTest[i] {
			correct++
		}
		if pred[i] == g.PredTest[i] {
			agree++
		}
	}
	acc := float64(correct) / float64(len(pred))
	if math.Abs(acc-g.AccuracyTest) > 0.05 {
		t.Errorf("test accuracy: got %.4f want %.4f (sklearn), Δ=%.3f > 0.05",
			acc, g.AccuracyTest, math.Abs(acc-g.AccuracyTest))
	}
	frac := float64(agree) / float64(len(pred))
	if frac < 0.9 {
		t.Errorf("label agreement with sklearn = %.3f, want ≥ 0.9", frac)
	}
	t.Logf("sklearn %s: accuracy go=%.4f sklearn=%.4f; sklearn-label-agreement=%.3f",
		gbmLoadGolden(t).Sklearn, acc, g.AccuracyTest, frac)
}

// §V16-EQUIV ANCHOR 2 (RESIDUAL/LOSS DECREASES). Training loss is monotonically
// non-increasing across boosting rounds (each tree fits the current residual)
// and reaches low training error on a learnable dataset.
func TestGBMTrainingLossMonotone(t *testing.T) {
	g := gbmLoadGolden(t).Regressor
	xtr := gbmRows(g.XTrain, g.NTrain, g.D)
	m := NewGradientBoostingRegressor(WithGBMNEstimators(60), WithGBMLearningRate(0.1), WithGBMMaxDepth(3))
	if err := m.Fit(xtr, g.YTrain); err != nil {
		t.Fatal(err)
	}
	loss := m.trainLoss
	if len(loss) != 61 {
		t.Fatalf("trainLoss length = %d, want nEstimators+1 = 61", len(loss))
	}
	for i := 1; i < len(loss); i++ {
		if loss[i] > loss[i-1]+1e-12 {
			t.Errorf("regressor MSE increased at round %d: %.6g > %.6g", i, loss[i], loss[i-1])
		}
	}
	if loss[len(loss)-1] >= loss[0] {
		t.Errorf("regressor MSE did not decrease: start %.4g end %.4g", loss[0], loss[len(loss)-1])
	}

	// classifier log loss on the two-moons training set.
	gc := gbmLoadGolden(t).Classifier
	xc := gbmRows(gc.XTrain, gc.NTrain, gc.D)
	c := NewGradientBoostingClassifier(WithGBMNEstimators(60), WithGBMLearningRate(0.1), WithGBMMaxDepth(3))
	if err := c.Fit(xc, gc.YTrain); err != nil {
		t.Fatal(err)
	}
	cl := c.trainLoss
	for i := 1; i < len(cl); i++ {
		if cl[i] > cl[i-1]+1e-12 {
			t.Errorf("classifier log loss increased at round %d: %.6g > %.6g", i, cl[i], cl[i-1])
		}
	}
	if cl[len(cl)-1] >= cl[0] {
		t.Errorf("classifier log loss did not decrease: start %.4g end %.4g", cl[0], cl[len(cl)-1])
	}
	t.Logf("regressor MSE %.4g→%.4g; classifier logloss %.4g→%.4g",
		loss[0], loss[len(loss)-1], cl[0], cl[len(cl)-1])
}

// §V16-EQUIV ANCHOR 3 (LEARNING-RATE / INIT LIMITS). learningRate=0 and
// nEstimators=0 both collapse the model to the initial constant F_0 = mean(y)
// (regressor) / base-rate probability (classifier) for every input, @1e-10.
func TestGBMInitLimits(t *testing.T) {
	x := [][]float64{{0, 1}, {1, 0}, {2, 3}, {3, 2}, {4, 5}}
	y := []float64{1, 2, 3, 4, 100} // mean = 22
	wantMean := 22.0
	for _, tc := range []struct {
		name string
		opts []GBMOption
	}{
		{"lr=0", []GBMOption{WithGBMLearningRate(0)}},
		{"nEstimators=0", []GBMOption{WithGBMNEstimators(0)}},
	} {
		m := NewGradientBoostingRegressor(tc.opts...)
		if err := m.Fit(x, y); err != nil {
			t.Fatal(err)
		}
		pred, _ := m.Predict(x)
		for i, p := range pred {
			if math.Abs(p-wantMean) > 1e-10 {
				t.Errorf("regressor %s: pred[%d]=%.12g, want F_0=%.12g", tc.name, i, p, wantMean)
			}
		}
	}

	// classifier: F_0 = log-odds of base rate → σ(F_0) = base rate for all rows.
	yc := []int{0, 0, 1, 1, 1} // base rate 3/5
	base := 3.0 / 5.0
	for _, tc := range []struct {
		name string
		opts []GBMOption
	}{
		{"lr=0", []GBMOption{WithGBMLearningRate(0)}},
		{"nEstimators=0", []GBMOption{WithGBMNEstimators(0)}},
	} {
		c := NewGradientBoostingClassifier(tc.opts...)
		if err := c.Fit(x, yc); err != nil {
			t.Fatal(err)
		}
		proba, _ := c.PredictProba(x)
		for i, p := range proba {
			if math.Abs(p-base) > 1e-10 {
				t.Errorf("classifier %s: proba[%d]=%.12g, want base rate %.12g", tc.name, i, p, base)
			}
		}
	}
}

// §V16-EQUIV ANCHOR 4 (WEAK-LEARNER CORRECTNESS). The gbmTree finds a
// hand-computed MSE-optimal split @1e-10, and a depth-1 stump on a step function
// splits exactly at the step.
func TestGBMWeakLearnerSplit(t *testing.T) {
	// Hand case: split must fall between x=2 and x=3 (threshold 2.5); left mean 1,
	// right mean 10 gives the maximal variance reduction.
	x := [][]float64{{1}, {2}, {3}, {4}}
	y := []float64{1, 1, 10, 10}
	idx := []int{0, 1, 2, 3}
	feat, thr, ok := bestGBMSplit(x, y, idx, 1)
	if !ok || feat != 0 || math.Abs(thr-2.5) > 1e-10 {
		t.Fatalf("bestGBMSplit: ok=%v feat=%d thr=%.12g, want feat=0 thr=2.5", ok, feat, thr)
	}
	tree := fitGBMTree(x, y, idx, 1, 1) // depth-1 stump
	if tree.root.leaf || math.Abs(tree.root.threshold-2.5) > 1e-10 {
		t.Fatalf("stump threshold = %.12g, want 2.5", tree.root.threshold)
	}
	pred := tree.Predict(x)
	want := []float64{1, 1, 10, 10}
	for i := range want {
		if math.Abs(pred[i]-want[i]) > 1e-10 {
			t.Errorf("stump pred[%d]=%.12g want %.12g", i, pred[i], want[i])
		}
	}

	// Step function: 6 points, step between x=2 and x=3.
	xs := [][]float64{{0}, {1}, {2}, {3}, {4}, {5}}
	ys := []float64{0, 0, 0, 10, 10, 10}
	st := fitGBMTree(xs, ys, []int{0, 1, 2, 3, 4, 5}, 1, 1)
	if math.Abs(st.root.threshold-2.5) > 1e-10 {
		t.Errorf("step stump threshold = %.12g, want 2.5", st.root.threshold)
	}
}

// §V16-EQUIV ANCHOR 5 (THE VALUE). On the nonlinear Friedman #1 target, GBM's
// test R² beats both a single regression-tree stump and OLS linear regression.
func TestGBMBeatsStumpAndOLS(t *testing.T) {
	g := gbmLoadGolden(t).Regressor
	xtr := gbmRows(g.XTrain, g.NTrain, g.D)
	xte := gbmRows(g.XTest, g.NTest, g.D)

	m := NewGradientBoostingRegressor(WithGBMNEstimators(100), WithGBMLearningRate(0.1), WithGBMMaxDepth(3))
	if err := m.Fit(xtr, g.YTrain); err != nil {
		t.Fatal(err)
	}
	gbmPred, _ := m.Predict(xte)
	gbmScore := gbmR2(g.YTest, gbmPred)

	// single stump: one full-data depth-1 regression tree.
	idx := make([]int, g.NTrain)
	for i := range idx {
		idx[i] = i
	}
	stump := fitGBMTree(xtr, g.YTrain, idx, 1, 1)
	stumpScore := gbmR2(g.YTest, stump.Predict(xte))

	// OLS baseline.
	var ols LinearRegression
	if err := ols.Fit(xtr, g.YTrain); err != nil {
		t.Fatal(err)
	}
	olsPred, err := ols.Predict(xte)
	if err != nil {
		t.Fatal(err)
	}
	olsScore := gbmR2(g.YTest, olsPred)

	if gbmScore <= stumpScore {
		t.Errorf("GBM R² %.4f not > stump R² %.4f", gbmScore, stumpScore)
	}
	if gbmScore <= olsScore {
		t.Errorf("GBM R² %.4f not > OLS R² %.4f", gbmScore, olsScore)
	}
	t.Logf("nonlinear test R²: GBM=%.4f  stump=%.4f  OLS=%.4f", gbmScore, stumpScore, olsScore)
}

// §V16-EQUIV ANCHOR 6 (SANITY). Shape/label/hyper-parameter validation,
// determinism, subsampling, and predict-before-fit errors.
func TestGBMSanity(t *testing.T) {
	x := [][]float64{{0}, {1}, {2}, {3}}
	y := []float64{0, 1, 2, 3}

	// empty / mismatched.
	if err := (&GradientBoostingRegressor{cfg: defaultGBMConfig()}).Fit(nil, nil); err == nil {
		t.Error("empty fit must error")
	}
	if err := NewGradientBoostingRegressor().Fit(x, []float64{0, 1}); err == nil {
		t.Error("mismatched X,y must error")
	}
	if err := NewGradientBoostingRegressor().Fit([][]float64{{0}, {1, 2}}, []float64{0, 1}); err == nil {
		t.Error("ragged X must error")
	}

	// hyper-parameter ranges.
	for _, bad := range []struct {
		name string
		opts []GBMOption
	}{
		{"lr<0", []GBMOption{WithGBMLearningRate(-0.1)}},
		{"maxDepth<1", []GBMOption{WithGBMMaxDepth(0)}},
		{"minSamplesLeaf<1", []GBMOption{WithGBMMinSamplesLeaf(0)}},
		{"subsample>1", []GBMOption{WithGBMSubsample(1.5)}},
		{"subsample<=0", []GBMOption{WithGBMSubsample(0)}},
		{"nEstimators<0", []GBMOption{WithGBMNEstimators(-1)}},
	} {
		if err := NewGradientBoostingRegressor(bad.opts...).Fit(x, y); err == nil {
			t.Errorf("%s must error", bad.name)
		}
	}

	// predict-before-fit.
	if _, err := NewGradientBoostingRegressor().Predict(x); err == nil {
		t.Error("regressor Predict before Fit must error")
	}
	if _, err := NewGradientBoostingClassifier().Predict(x); err == nil {
		t.Error("classifier Predict before Fit must error")
	}
	if _, err := NewGradientBoostingClassifier().PredictProba(x); err == nil {
		t.Error("classifier PredictProba before Fit must error")
	}

	// classifier label / degeneracy checks.
	if err := NewGradientBoostingClassifier().Fit(x, []int{0, 0, 0, 0}); err == nil {
		t.Error("single-class target must error")
	}
	if err := NewGradientBoostingClassifier().Fit(x, []int{0, 1, 2, 1}); err == nil {
		t.Error("non-binary label must error")
	}

	// determinism, including stochastic subsampling.
	g := gbmLoadGolden(t).Regressor
	xtr := gbmRows(g.XTrain, g.NTrain, g.D)
	fit := func() []float64 {
		m := NewGradientBoostingRegressor(WithGBMNEstimators(30), WithGBMSubsample(0.6), WithGBMSeed(7))
		if err := m.Fit(xtr, g.YTrain); err != nil {
			t.Fatal(err)
		}
		p, _ := m.Predict(xtr)
		return p
	}
	a, b := fit(), fit()
	for i := range a {
		if a[i] != b[i] {
			t.Fatalf("subsampled fit not deterministic at %d: %.17g vs %.17g", i, a[i], b[i])
		}
	}
}

// --- runnable Examples (§C13/§V19: per-type + per-method coverage) ---

// GradientBoostingRegressor fits an additive series of shallow trees to the
// residuals. On a clean step target 50 depth-1 stumps drive the predictions to
// the two plateau levels, 0 and 10.
func ExampleGradientBoostingRegressor() {
	x := [][]float64{{0}, {1}, {2}, {3}, {4}, {5}}
	y := []float64{0, 0, 0, 10, 10, 10}
	m := NewGradientBoostingRegressor(WithGBMNEstimators(50), WithGBMLearningRate(0.3), WithGBMMaxDepth(1))
	if err := m.Fit(x, y); err != nil {
		panic(err)
	}
	pred, err := m.Predict([][]float64{{0}, {5}})
	if err != nil {
		panic(err)
	}
	fmt.Printf("%.1f %.1f\n", pred[0], pred[1])
	// Output: 0.0 10.0
}

// GradientBoostingClassifier is binary gradient boosting under logistic loss.
// Trained on two clearly separated groups it labels a point near the second
// group as class 1 with probability above 0.5, and one near the first as class 0.
func ExampleGradientBoostingClassifier() {
	x := [][]float64{{0, 0}, {0.2, 0.1}, {5, 5}, {5.1, 4.9}}
	y := []int{0, 0, 1, 1}
	m := NewGradientBoostingClassifier()
	if err := m.Fit(x, y); err != nil {
		panic(err)
	}
	pred, err := m.Predict([][]float64{{5, 5}, {0, 0}})
	if err != nil {
		panic(err)
	}
	prob, err := m.PredictProba([][]float64{{5, 5}})
	if err != nil {
		panic(err)
	}
	fmt.Println(pred[0], pred[1], prob[0] > 0.5)
	// Output: 1 0 true
}
