package pytorch_test

import (
	"archive/zip"
	"bytes"
	"os"
	"testing"

	"github.com/jxsl13/goai/format/pytorch"
	"github.com/jxsl13/goai/tensor"
)

// TestLoadGolden loads a torch.save checkpoint (testdata/golden.pt, generated by
// PyTorch 2.x) and checks every tensor's dtype, shape and values — across F32,
// F64, F16, BF16 and int64 (widened), plus a dotted key.
func TestLoadGolden(t *testing.T) {
	got, err := pytorch.LoadFile("testdata/golden.pt")
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	type want struct {
		shape []int
		dt    tensor.Dtype
		vals  []float64
	}
	golden := map[string]want{
		"w32":            {[]int{2, 3}, tensor.F32, []float64{1.5, -2.0, 3.25, 4.0, 5.0, 6.5}},
		"w64":            {[]int{3}, tensor.F64, []float64{0.1, 0.2, 0.3}},
		"w16":            {[]int{4}, tensor.F16, []float64{1.0, 2.0, -0.5, 3.0}},
		"wbf16":          {[]int{2}, tensor.BF16, []float64{1.0, -1.0}},
		"wi64":           {[]int{2, 2}, tensor.F64, []float64{10, 20, 30, 40}},
		"nested.inner.b": {[]int{2}, tensor.F32, []float64{7.0, 8.0}},
	}
	if len(got) != len(golden) {
		t.Fatalf("got %d tensors, want %d: %v", len(got), len(golden), keys(got))
	}
	for name, w := range golden {
		tn := got[name]
		if tn == nil {
			t.Fatalf("missing tensor %q", name)
		}
		if tn.Dtype() != w.dt {
			t.Errorf("%s: dtype %v, want %v", name, tn.Dtype(), w.dt)
		}
		if !eq(tn.Shape(), w.shape) {
			t.Errorf("%s: shape %v, want %v", name, tn.Shape(), w.shape)
		}
		if tn.Numel() != len(w.vals) {
			t.Fatalf("%s: numel %d, want %d", name, tn.Numel(), len(w.vals))
		}
		for i, v := range w.vals {
			if g := valAt(tn, i); g != v {
				t.Errorf("%s[%d] = %v, want %v", name, i, g, v)
			}
		}
	}
}

// TestRejectsCodeExecution: a pickle naming a disallowed global (the classic RCE
// vector, e.g. os.system) must be refused, not executed.
func TestRejectsCodeExecution(t *testing.T) {
	// minimal hostile pickle: PROTO 2, GLOBAL 'posix system', ... — the loader
	// must error at the GLOBAL check. Build the data.pkl and wrap it in a zip.
	hostile := []byte{0x80, 2, 'c'}
	hostile = append(hostile, []byte("posix\nsystem\n")...)
	hostile = append(hostile, '.')
	arch := zipWith(t, "m/data.pkl", hostile)
	_, err := pytorch.Load(bytes.NewReader(arch), int64(len(arch)))
	if err == nil {
		t.Fatal("hostile global accepted — code-execution vector not closed")
	}
}

func valAt(t *tensor.Tensor, flatIdx int) float64 {
	idx := tensor.Unravel(flatIdx, t.Shape())
	return t.AtF64(idx...)
}

func keys(m map[string]*tensor.Tensor) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

func eq(a []int, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// zipWith builds a minimal STORED zip archive containing one entry.
func zipWith(t *testing.T, name string, data []byte) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	w, err := zw.CreateHeader(&zip.FileHeader{Name: name, Method: zip.Store})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := w.Write(data); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// FuzzLoad throws random bytes at the loader: it must never panic and never
// execute anything — only return a tensor map or an error. Seeded with the
// golden archive so the fuzzer explores valid-ish mutations.
func FuzzLoad(f *testing.F) {
	if b, err := os.ReadFile("testdata/golden.pt"); err == nil {
		f.Add(b)
	}
	f.Add([]byte{0x80, 2, '}', '.'})
	f.Fuzz(func(t *testing.T, data []byte) {
		_, _ = pytorch.Load(bytes.NewReader(data), int64(len(data)))
	})
}

// TestLoadParameter covers whole-module saves that box weights in nn.Parameter
// (torch._utils._rebuild_parameter wrapping _rebuild_tensor_v2).
func TestLoadParameter(t *testing.T) {
	got, err := pytorch.LoadFile("testdata/param.pt")
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	p := got["p"]
	if p == nil || p.Numel() != 3 || p.AtF64(0) != 1.5 || p.AtF64(2) != 3.5 {
		t.Fatalf("parameter 'p' wrong: %v", p)
	}
	if got["t"] == nil || got["t"].AtF64(1) != 8.0 {
		t.Fatalf("tensor 't' wrong")
	}
}

// TestLoadProtocols covers pickle protocols 4 and 5 (MEMOIZE / STACK_GLOBAL /
// FRAME), so the loader handles any torch.save output, not just the default 2.
func TestLoadProtocols(t *testing.T) {
	for _, p := range []string{"testdata/proto4.pt", "testdata/proto5.pt"} {
		got, err := pytorch.LoadFile(p)
		if err != nil {
			t.Fatalf("%s: %v", p, err)
		}
		a := got["a.weight"]
		if a == nil || a.Numel() != 6 || a.AtF64(0, 0) != 0 || a.AtF64(1, 2) != 5 {
			t.Fatalf("%s: a.weight wrong: %v", p, a)
		}
		if got["b"] == nil || got["b"].AtF64(0) != 7 {
			t.Fatalf("%s: b wrong", p)
		}
	}
}

// FuzzPickle fuzzes the RESTRICTED UNPICKLER, which FuzzLoad cannot reach.
//
// FuzzLoad mutates the whole ZIP container, so a mutated byte almost always
// breaks the local header, central directory or CRC and Load bails out in
// archive/zip long before any pickle opcode is interpreted — 2.25M execs found
// nothing while hand-written pickles crashed the interpreter instantly. This
// target takes RAW data.pkl bytes and builds a fresh, valid zip around them
// inside the fuzz function, so every mutation lands on pickle bytes and the
// interpreter is actually explored. Storage blobs are supplied so tensor
// materialization is reachable too.
//
// Invariant: no input may panic. Any error is acceptable.
func FuzzPickle(f *testing.F) {
	f.Add([]byte{0x80, 2, '}', '.'})
	f.Add([]byte{0x80, 4, 0x94, '.'})                // MEMOIZE empty-stack peek
	f.Add([]byte{0x80, 2, 'q', 0, '.'})              // BINPUT empty-stack peek
	f.Add([]byte{0x80, 2, 'r', 0, 0, 0, 0, '.'})     // LONG_BINPUT empty-stack peek
	f.Add([]byte{0x80, 2, '(', 'u', '.'})            // SETITEMS empty-stack peek
	f.Add([]byte{0x80, 2, 's', '.'})                 // SETITEM pop underflow
	f.Add([]byte{0x80, 2, 'K', 1, 'K', 2, 's', '.'}) // SETITEM empty-stack target
	// Shape-product overflow: (2^62, 4) wraps to exactly 2^64 ≡ 0.
	f.Add(hostileShapePickle([]int64{1 << 62, 4}, []int64{4, 1}, 4))

	f.Fuzz(func(t *testing.T, pkl []byte) {
		var buf bytes.Buffer
		zw := zip.NewWriter(&buf)
		for name, data := range map[string][]byte{
			"archive/data.pkl": pkl,
			"archive/data/0":   make([]byte, 64),
			"archive/data/1":   make([]byte, 64),
		} {
			w, err := zw.CreateHeader(&zip.FileHeader{Name: name, Method: zip.Store})
			if err != nil {
				t.Skip()
			}
			if _, err := w.Write(data); err != nil {
				t.Skip()
			}
		}
		if err := zw.Close(); err != nil {
			t.Skip()
		}
		b := buf.Bytes()
		_, _ = pytorch.Load(bytes.NewReader(b), int64(len(b)))
	})
}
